steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['get', 'google.golang.org/grpc']
  env: ['PROJECT_ROOT=github.com/eqinox76/RiseAndFallOfEmpires']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', 'rafoe.go']
  env: ['PROJECT_ROOT=github.com/eqinox76/RiseAndFallOfEmpires']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', 'client/observer/rafoe-observer.go']
  env: ['PROJECT_ROOT=github.com/eqinox76/RiseAndFallOfEmpires']
artifacts:
  objects:
    location: 'gs://riseandfallofempires/'
    paths: ['rafoe', 'rafoe-observer']
