// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rafoe-server.proto

/*
	Package riseandfall is a generated protocol buffer package.

	It is generated from these files:
		rafoe-server.proto

	It has these top-level messages:
*/
package riseandfall

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import riseandfall1 "."
import riseandfall2 "."

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GameServer service

type GameServerClient interface {
	// get all game states streamed
	Observe(ctx context.Context, in *riseandfall1.ID, opts ...grpc.CallOption) (GameServer_ObserveClient, error)
	// control one or multiple clients and get the current game state
	StrategyClient(ctx context.Context, opts ...grpc.CallOption) (GameServer_StrategyClientClient, error)
}

type gameServerClient struct {
	cc *grpc.ClientConn
}

func NewGameServerClient(cc *grpc.ClientConn) GameServerClient {
	return &gameServerClient{cc}
}

func (c *gameServerClient) Observe(ctx context.Context, in *riseandfall1.ID, opts ...grpc.CallOption) (GameServer_ObserveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GameServer_serviceDesc.Streams[0], c.cc, "/riseandfall.GameServer/Observe", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameServerObserveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GameServer_ObserveClient interface {
	Recv() (*riseandfall1.Space, error)
	grpc.ClientStream
}

type gameServerObserveClient struct {
	grpc.ClientStream
}

func (x *gameServerObserveClient) Recv() (*riseandfall1.Space, error) {
	m := new(riseandfall1.Space)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameServerClient) StrategyClient(ctx context.Context, opts ...grpc.CallOption) (GameServer_StrategyClientClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GameServer_serviceDesc.Streams[1], c.cc, "/riseandfall.GameServer/StrategyClient", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameServerStrategyClientClient{stream}
	return x, nil
}

type GameServer_StrategyClientClient interface {
	Send(*riseandfall2.Command) error
	Recv() (*riseandfall1.Space, error)
	grpc.ClientStream
}

type gameServerStrategyClientClient struct {
	grpc.ClientStream
}

func (x *gameServerStrategyClientClient) Send(m *riseandfall2.Command) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameServerStrategyClientClient) Recv() (*riseandfall1.Space, error) {
	m := new(riseandfall1.Space)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GameServer service

type GameServerServer interface {
	// get all game states streamed
	Observe(*riseandfall1.ID, GameServer_ObserveServer) error
	// control one or multiple clients and get the current game state
	StrategyClient(GameServer_StrategyClientServer) error
}

func RegisterGameServerServer(s *grpc.Server, srv GameServerServer) {
	s.RegisterService(&_GameServer_serviceDesc, srv)
}

func _GameServer_Observe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(riseandfall1.ID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServerServer).Observe(m, &gameServerObserveServer{stream})
}

type GameServer_ObserveServer interface {
	Send(*riseandfall1.Space) error
	grpc.ServerStream
}

type gameServerObserveServer struct {
	grpc.ServerStream
}

func (x *gameServerObserveServer) Send(m *riseandfall1.Space) error {
	return x.ServerStream.SendMsg(m)
}

func _GameServer_StrategyClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServerServer).StrategyClient(&gameServerStrategyClientServer{stream})
}

type GameServer_StrategyClientServer interface {
	Send(*riseandfall1.Space) error
	Recv() (*riseandfall2.Command, error)
	grpc.ServerStream
}

type gameServerStrategyClientServer struct {
	grpc.ServerStream
}

func (x *gameServerStrategyClientServer) Send(m *riseandfall1.Space) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameServerStrategyClientServer) Recv() (*riseandfall2.Command, error) {
	m := new(riseandfall2.Command)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GameServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "riseandfall.GameServer",
	HandlerType: (*GameServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Observe",
			Handler:       _GameServer_Observe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StrategyClient",
			Handler:       _GameServer_StrategyClient_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rafoe-server.proto",
}

func init() { proto.RegisterFile("rafoe-server.proto", fileDescriptorRafoeServer) }

var fileDescriptorRafoeServer = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x4a, 0x4c, 0xcb,
	0x4f, 0xd5, 0x2d, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x2e, 0xca, 0x2c, 0x4e, 0x4d, 0xcc, 0x4b, 0x49, 0x4b, 0xcc, 0xc9, 0x91, 0xe2, 0x2e, 0x2e, 0x48,
	0x4c, 0x4e, 0x85, 0xc8, 0x48, 0xf1, 0x26, 0xe7, 0xe7, 0xe6, 0x26, 0xe6, 0xa5, 0x40, 0xb8, 0x46,
	0x4d, 0x8c, 0x5c, 0x5c, 0xee, 0x89, 0xb9, 0xa9, 0xc1, 0x60, 0xdd, 0x42, 0x46, 0x5c, 0xec, 0xfe,
	0x49, 0x60, 0x93, 0x84, 0xf8, 0xf5, 0x90, 0xcc, 0xd0, 0xf3, 0x74, 0x91, 0x12, 0x42, 0x11, 0x08,
	0x06, 0x99, 0xa9, 0xc4, 0x60, 0xc0, 0x28, 0xe4, 0xc0, 0xc5, 0x17, 0x5c, 0x52, 0x94, 0x58, 0x92,
	0x9a, 0x5e, 0xe9, 0x9c, 0x93, 0x99, 0x9a, 0x57, 0x22, 0x24, 0x82, 0xa2, 0xd2, 0x19, 0x62, 0x21,
	0x76, 0xfd, 0x1a, 0x8c, 0x06, 0x8c, 0x4e, 0x02, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7,
	0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x8c, 0xc7, 0x72, 0x0c, 0x49, 0x6c, 0x60, 0xd7, 0x19, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x48, 0xa2, 0x68, 0xda, 0xdc, 0x00, 0x00, 0x00,
}
